no local and retab

diff --git a/plotGNU b/plotGNU
--- a/plotGNU
+++ b/plotGNU
@@ -28,71 +28,71 @@ help
 
 plot(){
 
-	# -- determine number of columns in input data
-	ncol=0
+  # -- determine number of columns in input data
+  ncol=0
   narr=$(awk -F " " "{print NF}" "${data}")
   for n in ${narr[@]} ; do
     [ $ncol -lt $n ] && ncol=$n
   done
 
-	[ "${verbosity}" -gt 0 ] && printf "NCOL            = %s\n" "${ncol}"
+  [ "${verbosity}" -gt 0 ] && printf "NCOL            = %s\n" "${ncol}"
 
-	echo "${preplt} ; plot for [c=2:${ncol}] ""'""${data}""'"" u 1:c ${gnuplot_options}" | gnuplot -persist
+  echo "${preplt} ; plot for [c=2:${ncol}] ""'""${data}""'"" u 1:c ${gnuplot_options}" | gnuplot -persist
 
 }
 
 # -- raise an error message and exits.
 die() {
 
-  local exit_code=1
-  local error_message="$1"
+  exit_code=1
+  error_message="$1"
 
-	echo "${PROGRAM}: ${error_message}" 1>&2
+  echo "${PROGRAM}: ${error_message}" 1>&2
 
   exit "${exit_code}"
 }
 
 main() {
 
-	while :; do
-		case $1 in
-			-h|-\?|--help)
-				usage
-				exit 0
-				;;
+  while :; do
+    case $1 in
+      -h|-\?|--help)
+        usage
+        exit 0
+        ;;
 
-			-v|--verbose)
-				verbosity=$((verbosity + 1))
-				;;
+      -v|--verbose)
+        verbosity=$((verbosity + 1))
+        ;;
 
-			-o | --opt | --options)
-				[ "$2" ] && gnuplot_options="${2}" && shift || die 'ERROR: "--options" requires a non-empty option argument.'
-				;;
-			-o= | --opt= | --options=)
-				die 'ERROR: "--options" requires a non-empty argument.'
-				;;
-			-o=?* | --opt=?* | --options=?*)
-				gnuplot_option="${1#*=}"
-				;;
+      -o | --opt | --options)
+        [ "$2" ] && gnuplot_options="${2}" && shift || die 'ERROR: "--options" requires a non-empty option argument.'
+        ;;
+      -o= | --opt= | --options=)
+        die 'ERROR: "--options" requires a non-empty argument.'
+        ;;
+      -o=?* | --opt=?* | --options=?*)
+        gnuplot_option="${1#*=}"
+        ;;
 
-			-p | --pre | --preplot)
-				[ "$2" ] && preplt="${2}" && shift || die 'ERROR: "--preplot" requires a non-empty option argument.'
-				;;
-			-p= | --pre= | --preplot=)
-				die 'ERROR: "--preplot" requires a non-empty argument.'
-				;;
-			-p=?* | --pre=?* | --preplot=?*)
-				preplt="${1#*=}"
-				;;
+      -p | --pre | --preplot)
+        [ "$2" ] && preplt="${2}" && shift || die 'ERROR: "--preplot" requires a non-empty option argument.'
+        ;;
+      -p= | --pre= | --preplot=)
+        die 'ERROR: "--preplot" requires a non-empty argument.'
+        ;;
+      -p=?* | --pre=?* | --preplot=?*)
+        preplt="${1#*=}"
+        ;;
 
-			--)
-				shift
-				break
-				;;
-			-?*)
-				printf 'WARN: Unknown option (ignored): %s\n' "${1}"
-				;;
-			*)
+      --)
+        shift
+        break
+        ;;
+      -?*)
+        printf 'WARN: Unknown option (ignored): %s\n' "${1}"
+        ;;
+      *)
         # -- loop over supplied data files
         while
 
@@ -116,12 +116,12 @@ main() {
 
         break
 
-				;;
+        ;;
 
-			esac
-			shift
+      esac
+      shift
 
-	done
+  done
 
 }
 
